# -*- coding: utf-8 -*-
"""AC-22-only split execution for spatial-platform commit 72b88d2.

Goal (per user plan): rewrite history so that
  Commit A = AC-22 only  = [P3-milestone-status.md Step-11 AC-22 flip (PROVEN twin),
                            P3.1-...-verification-report.md AC-22 row flip,
                            tests/unit/test_p3_trajectory_optimization.cpp AC-22 twin block]
  Deferred (uncommitted) = Step-12 CLI E2E: test_cli_sparse_correction_e2e.cpp,
                            tests/CMakeLists.txt activation, milestone Step-12 CLI paragraph.

Invariant checks are made at every step; any mismatch aborts without side effects.

Current state precondition (verified): HEAD == fbef42b (parent); worktree holds ALL the
72b88d2 content uncommitted.
"""
import subprocess, io, os, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

REPO = r'C:\Code\ClaudeDot\spatial-platform'
PARENT = 'fbef42b'      # current HEAD == parent
HEAD   = '72b88d2'      # the commit being split (content lives in the worktree)
MIL = r'docs/architecture/P3-milestone-status.md'
REP = r'docs/architecture/P3.1-production-sparse-correction-verification-report.md'
TST = r'tests/unit/test_p3_trajectory_optimization.cpp'
CLI = r'tests/unit/test_cli_sparse_correction_e2e.cpp'
CMA = r'tests/CMakeLists.txt'

def git(*a, check=True):
    r = subprocess.run(['git'] + list(a), cwd=REPO, capture_output=True)
    if check and r.returncode != 0:
        raise RuntimeError('git %s failed:\n%s' % (' '.join(a), r.stderr.decode('utf-8', 'replace')))
    return r.stdout.decode('utf-8', 'replace')

def blob(rev, path):
    return git('show', rev + ':' + path)

def rb(path):
    with open(os.path.join(REPO, path), 'rb') as f:
        return f.read()

def wb(path, data):
    with open(os.path.join(REPO, path), 'wb') as f:
        f.write(data)

def msg(s):
    print('\n===== %s =====' % s)

# ---------------------------------------------------------------------------
msg('0) VERIFY PRECONDITIONS (refuse on any surprise)')
assert git('rev-parse', 'HEAD').strip() == PARENT, 'HEAD must already be the parent (split-ready)'
print('HEAD =', git('rev-parse', 'HEAD').strip(), '(== parent, good)')

# Worktree must contain the full 72b88d2 content for the 6 relevant paths.
for p in (MIL, REP, TST, CLI, CMA):
    w = rb(p)
    h = rb((git('show', HEAD + ':' + p).encode('utf-8'))) if False else None
    want = subprocess.run(['git', 'show', HEAD + ':' + p], cwd=REPO, capture_output=True).stdout
    same = (w == want)
    print('  worktree==HEAD %-55s : %s (%d bytes)' % (p, same, len(w)))
    assert same, 'worktree file %s does not match HEAD blob — abort' % p
print('  all 6 files byte-identical to HEAD content in worktree (nothing lost)')

# ---------------------------------------------------------------------------
msg('1) Save the FULL 72b88d2 milestone (still has Step-12 CLI paragraph) for later restore')
mil_full_head = rb(MIL)
print('saved full-HEAD milestone bytes=%d (Step-12 present=%s)'
      % (len(mil_full_head), b'Step 12' in mil_full_head))

# ---------------------------------------------------------------------------
msg('2) Build the AC-22-only milestone = parent + ONLY the Step-11 AC-22 flip')
ac22_mil_expected = rb(r'tmp\ac22_milestone_only.md')  # already generated byte-verified
# confirm it is derived from parent + flip, no Step-12
parent_mil = blob(PARENT, MIL).encode('utf-8')
assert b'Step 12' not in ac22_mil_expected, 'AC-22-only milestone must have NO Step-12'
assert b'AC-22 (PROVEN 2026-09-12' in ac22_mil_expected, 'AC-22 twin PROVEN must be present'
assert parent_mil.count(b'Remaining P3.1 items: AC-22 (NOT started per GO)') == 1
# The flip is exactly this one anchor in the parent's Step-11 bullet tail.
anchor = b'Remaining P3.1 items: AC-22 (NOT started per GO)'
assert anchor in parent_mil
# the AC-22-only version differs from parent ONLY by that flip:
import re
flip = ac22_mil_expected  # trust the verified tmp file

print('AC-22-only milestone bytes=%d lines=%d  Step-12=%s  AC-22-PROVEN-twin=%s'
      % (len(flip), flip.count(b'\n') + 1, b'Step 12' in flip,
         b'AC22_DeterministicSecondRunThroughProductionSurface' in flip))

# ---------------------------------------------------------------------------
msg('3) Build the AC-22-only report = parent + ONLY the AC-22 row flip (single-row diff)')
parent_rep = blob(PARENT, REP)
old_row = '| AC-22: Deterministic second run | No double-run | NOT PROVEN |'
new_row = ('| AC-22: Deterministic second run | Twin double-run via `Engine::RunPipeline` '
           '(two fresh projects, real GTSAM seams), Debug EXIT 0 + Release EXIT 0 | PROVEN |')
assert parent_rep.count(old_row) == 1, 'report AC-22 NOT-PROVEN row must be unique'
ac22_rep = parent_rep.replace(old_row, new_row, 1)
assert 'Step 12' not in ac22_rep and 'CLI E2E' not in ac22_rep, 'report must stay AC-22 only'
print('AC-22-only report bytes=%d  row flipped=%s' % (len(ac22_rep.encode('utf-8')), 'PROVEN' in ac22_rep))

# ---------------------------------------------------------------------------
msg('4) Stage EXACTLY the 3 AC-22 files')
wb(MIL, flip)
wb(REP, ac22_rep.encode('utf-8'))
for p in (MIL, REP, TST):
    git('add', '--', p)

staged = git('diff', '--cached', '--name-only').strip().split('\n')
staged = [s for s in staged if s.strip()]
print('STAGED (must be exactly 3):')
for s in staged:
    print('   ', s)
assert staged == [MIL, REP, TST], 'must stage exactly 3 AC-22 files (got %d)' % len(staged)

# ---------------------------------------------------------------------------
msg('5) Commit A (AC-22 only)')
git('commit', '-m',
    'feat(tests): AC-22 deterministic-second-run twin PROVEN through real GTSAM seams '
    '(AC-22-only split; Step-12 CLI E2E deferred)\n'
    '\n'
    'AC-22 (Deterministic second run) flipped NOT PROVEN -> PROVEN. New '
    '`AC22_DeterministicSecondRunThroughProductionSurface` twin in '
    'tests/unit/test_p3_trajectory_optimization.cpp: two fresh '
    '`Engine::RunPipeline("p3_sparse_correction")` invocations through REAL GTSAM seams '
    '(two independent projects, bit-identical pinned inputs), semantic equivalence + small '
    'absolute GTSAM tolerances asserted, N5 duplicate-refusal re-proven; Debug EXIT 0, '
    'Release EXIT 0; full trajectory 23/23 in both configs (projection twin). '
    'P3-milestone-status.md Step-11 AC-22 flip + P3.1 verification report AC-22 row updated. '
    'Step-12 CLI E2E (test_cli_sparse_correction_e2e.cpp + test activation + CLI paragraph) '
    'deliberately deferred -> left uncommitted in the working tree.')

print('Committed as', git('rev-parse', 'HEAD').strip())

# ---------------------------------------------------------------------------
msg('6) Verify commit A contains EXACTLY the 3 AC-22 paths')
names = git('show', '--name-only', '--format=', 'HEAD').strip().split('\n')
names = [n for n in names if n.strip()]
print('commit A files:')
for n in names:
    print('   ', n)
assert sorted(names) == sorted([MIL, REP, TST]), 'commit A must contain exactly 3 AC-22 files'
# committed milestone has NO Step-12:
assert b'Step 12' not in git('show', 'HEAD:' + MIL).encode('utf-8')
print('OK: commit A = exactly [milestone(AC-22), report(AC-22), twin-test] — no CLI E2E content committed')

# ---------------------------------------------------------------------------
msg('7) Restore the CONTENT PATCH for tracked deferred files, keep them UNCOMMITTED')
# Deferred (Step-12 CLI E2E) lives on as uncommitted worktree changes:
#   (a) milestone: restore the full Step-12 CLI paragraph on top of the committed AC-22-only
#       milestone  -> worktree milestone = AC-22 (committed) + Step-12 (uncommitted)
#   (b) tests/CMakeLists.txt + test_cli_sparse_correction_e2e.cpp remain as-is (untracked/unsagged)
wb(MIL, mil_full_head)          # milestone back to full Step-12 content (diff vs HEAD shows Step-12)
# ensure report is exactly the committed version (no stray diff)
subprocess.run(['git', 'add', '--intent-to-add', CLI], cwd=REPO, capture_output=True)

print('\n=== git status --short (deferred = uncommitted) ===')
print(git('status', '--short'))
print('\n=== worktree milestone: Step-12 present (uncommitted) ===')
print('  Step 12 in worktree milestone :', b'Step 12' in rb(MIL))
print('  committed HEAD milestone 12   :', git('log', '-1', '--format=%h %s'))

# ---------------------------------------------------------------------------
msg('8) FINAL SANITY: git log + staged set + deferred set')
print('git log --oneline -3:')
print(git('log', '--oneline', '-3'))
print('\nStaged (must be empty list):', repr([s for s in git('diff', '--cached', '--name-only').strip().split('\n') if s.strip()]))
print('Deferred files still present in worktree:')
for p in (CLI, CMA):
    print('   %-55s tracked=%s' % (p, os.path.exists(os.path.join(REPO, p))))
print('\nDONE — AC-22-only commit A created; Step-12 CLI E2E deferred (uncommitted).')
